### ISSUE TITLE
Set a user-agent when fetching piwik.js to avoid firewalls blocking the request

### ISSUE THREAD

**Issue by k0nsl** [piwik/tracker-proxy#1]
I have one suggestion: when fetching piwik.js via the proxy script we should set a user agent string as many WAFs will block requests which leaves this string empty. I will attach an example of how it can look when (for example) CloudFlare blocks it via their WAF.
![piwik-empty-user-agent01_k0nsl](https://cloud.githubusercontent.com/assets/2517921/6587891/7f84267a-c78a-11e4-9379-a044ffe1e37d.png)

Just a thought :)

**Comment by mattab** [comment]
Thanks for suggestion! this was implemented in https://github.com/piwik/tracker-proxy/pull/7/files
