### ISSUE TITLE
Remote IP ignored, piwik records the server IP instead

### ISSUE THREAD

**Issue by jsmad** [piwik/tracker-proxy#11]
I've installed the proxy and it started recording clicks right away.

Unfortunately, ALL clicks seem to come from my server IP address.

I did some debugging, and looked at the URL called by the proxy, which correctly shows the remote IP address of the user in the parameters:

```
piwik.php?cip=xxx.xxx.xxx.xxx
```

But that seems to be ignored and instead piwik records the IP address that runs the proxy (thus the server IP address).

Any help would be appreciated.

**Comment by mikaelmeulle** [comment]
hello, i've got the same problem. it comed from the function getIpString in the file core/Tracker/Request.php

the  test on isAuthenticated() fail and the Ip is then taken from the header of the resquest (which is you server in your case)
hope that helps

Mikael

**Comment by jsmad** [comment]
I think the problem is that I forgot to give "Admin" access to the user "UserTrackingAPI" for all my websites, I did this only for one site.

I've now set admin access to all sites and I'll be tracking them to see if they properly record the remote IP address or not.

**Comment by mattab** [comment]
It just works. If not, please leave a comment / reopen this issue
