### ISSUE TITLE
SSL issue with Cloudflare

### ISSUE THREAD

**Issue by drenkan** [piwik/tracker-proxy#13]
So I first want to say thanks for all the awesome work on this plugin. I don´t know if this is the right forum for this question but I´d rather try.

I am currently using the tracker-proxy on a server with DNS on Cloudflare, everything works great! But then I wanted to track also https, so I activated SSL on cloudflare (SSL Flexible_). At the same moment I activated it all tracking on my Piwik installation stops working. The proxy script cant deliver piwik.js (file_get_contents) and gives the error message *Cant fetch piwik.js_ or something like that. If I deactivate SSL it starts working again immediately. 

So I tried adding the pull requests (Added User Agent in JS request, then Use cURL if fopen is not available). But adding those doesnt seem to help. I have allow_url_fopen = On, the server is PHP/5.4.39-0+deb7u1. It just seems as though as soon as I turn on SSL, the script cant execute file_get_contents with an absolute path (eg $Piwik_URL + piwik.js). A relative path (eg piwik.js since its in the same folder) works but that doesnt get the tracking going. Neither does cURL even though its enabled and should work. If I put the tracker-proxy on another server with SSL the tracking works, it just doesnt seem to work with Cloudflare, which I need it to do.

So do you guys know any thinkable solutions to this? Could it be the SSL-type is incompatible? Is it Cloudflare or is it a server setting (eg. php.ini). I´ve had someone suggest maybe extension=php_openssl.dll needs to be set. I´ve tried all possible settings in config.ini on the piwik server without success. 

Im thankful for any pointers or tips towards bringing this problem to a solution. My knowledge around php and server configuration is not the best. But im working on it!

*Flexible SSL -- SSL _between the visitor and CloudFlare -- visitor sees HTTPS on your site, but no SSL between CloudFlare and your web server. You don't need to have an SSL cert on your web server, but your visitors will still see the site as being HTTPS enabled._

**Comment by braekling** [comment]
Hi drenkan,

maybe this thread may help: https://wordpress.org/support/topic/not-tracking-when-behind-cloudflare-with-flexible-ssl?replies=6

Otherwise: Please make sure Piwik is available using the same protocols as your blog. E.g., if your blog can be reached using HTTP and HTTPS, Piwik should also offer HTTP and HTTPS. Also avoid redirects from HTTP to HTTPS. 

If you want to force the tracking code to use SSL always, use the protocol expert setting of WP-Piwik. This will change the tracking code from "//www.example.com" to "https://www.example.com".

**Comment by mattab** [comment]
@braekling gave some pointers. if you still have the issue please reopen or create a new issue, we'll try to help
