### ISSUE TITLE
Problems on certain servers: piwik.php is loading 5-6 seconds

### ISSUE THREAD

**Issue by flobox** [piwik/tracker-proxy#14]
Hey guys.

On some servers (Hosteurope) where the piwik.php was uploaded I am having problems with long loading times of the piwik.php. In these cases everything is tracked correctly as far as I can tell, BUT the loading time is always 5-6 seconds.

This occurs just at Hosteurope right now - on other sites with a different hosting company this does not occur.

I am trying a lot of things already - do you guys have any idea what to check?!

**Comment by halfdan** [comment]
Can you provide more information about the environment? Version of piwik,
php, MySQL,  etc.

**Comment by flobox** [comment]
I am using Piwik 2.1.15 also on a Hosteurope webhosting package (PHP 5.6) - here called host system. 

The site where I am using the tracker-proxy script is also on a Hosteurope webhosting package (B system) - but a seperate one. (PHP 5.6)

As said this just occurs on the B system. For sites which are hosted at different webhosters (also PHP 5.6) and are using the teacker-proxy everything runs smoothly and fast. So I am assuming it is not caused by the host system?!?

**Comment by flobox** [comment]
SOLVED! It seems to be an issue between two Hosteurope packages...some internal communication / firewall problem?

If I put the host system on a different webserver (NOT Hosteurope) everything is working fine!
