### ISSUE TITLE
file_get_contents issues, used CURL instead

### ISSUE THREAD

**Issue by jsmad** [piwik/tracker-proxy#15]
I'm using piwik and the tracker proxy script under php 5.4.16 and I was having considerable delays with the file_get_contents, when used with HTTPS urls.

Each file_get_contents call would cause 5+ seconds, but because the function is called twice it caused a delay of over 10 seconds.

I solved the delay problem by using CURL instead. I replaced the file_get_contents call with this:

```php
function file_get_contents2($url) {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
        curl_setopt($ch, CURLOPT_HEADER, false);
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
        curl_setopt($ch, CURLOPT_TIMEOUT, 5);
        $result = curl_exec($ch);
        curl_close($ch);
        return $result;
}
```

Extra modifications that I also did:

The timeout variable was no longer needed so I removed it. I'm using the curl timout parameter.

The curl ssl_verifypeer is set to false because my piwik is running on the same server but different virtual domain, so there was no real reason to verify the certificate of local host and that saves a few milliseconds. But those who load it over the internet may want to enable it.

I made extra modifications to step 1.

In step 2, I simplified the script by removing the code for old php versions and enforced a 204 code like this:

```php
sendHeader("Content-Type: image/gif");
http_response_code(204);
echo file_get_contents2($url);
```

I hope my experience is of help to somebody.

Thank you.

**Comment by mattab** [comment]
@jsmad can you check this pull request and comment there? https://github.com/piwik/tracker-proxy/pull/3/files I would like to merge it soon. Thanks for your feedback and/or contributions to this PR!

**Comment by mattab** [comment]
Added support for CURL in: https://github.com/piwik/tracker-proxy/pull/21/files

if you manage to test the PR, feedback would be appreciated!
