### ISSUE TITLE
curl instead of file_get_contents ?

### ISSUE THREAD

**Issue by centminmod** [piwik/tracker-proxy#16]
From https://forum.piwik.org/t/slow-10-seconds-loading-of-piwiks-url/18189 doesn't seem tracker-proxy piwik.php file has had any updates for using curl and HTTPS based piwik installs ?

**Comment by jsmad** [comment]
In case it helps, I use this replacement function:

```php
function file_get_contents2($url) {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
        curl_setopt($ch, CURLOPT_HEADER, false);
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
        curl_setopt($ch, CURLOPT_TIMEOUT, 5);
        if(isset($_SERVER["HTTP_USER_AGENT"]))
                curl_setopt($ch, CURLOPT_USERAGENT, $_SERVER["HTTP_USER_AGENT"]);
        $result = curl_exec($ch);
        curl_close($ch);
        return $result;
}
```

Once added into the php file, replace the file_get_contents() functions with file_get_contents2() and everything should work as before but the script will use curl instead.

The above works great with HTTPS and latest TLS v1.2 encryption.

**Comment by mattab** [comment]
See this PR which we will merge soon and will add curl support https://github.com/piwik/tracker-proxy/pull/3/files

**Comment by mattab** [comment]
Added support for CURL in: https://github.com/piwik/tracker-proxy/pull/21/files

if you manage to test the PR, feedback would be appreciated!
