### ISSUE TITLE
file_get_contents error

### ISSUE THREAD

**Issue by ytlevine** [piwik/tracker-proxy#18]
FYI, still getting an error on this line:
$content = file_get_contents($url, 0, $ctx); (line 110 in the code here)

Error message looks like this: 

> PHP Warning:  file_get_contents(https://my/piwikurl.com/piwik.php?cip=x.x.x.x&amp;token_auth=xxxx&amp;action_name=Title+Name&amp;idsite=2&amp;rec=1&amp;r=052799&amp;h=14&amp;m=35&amp;s=26&amp;url=https%3A%2F%2Fsite.com%2F&amp;urlref=https%3A%2F%2Fwww.google.ca%2F&amp;_id=a61f60e4cf37dea2&amp;_idts=1462127727&amp;_idvc=1&amp;_idn=0&amp;_refts=1462127727&amp;_viewts=1462127727&amp;_ref=https%3A%2F%2Fwww.google.ca%2F&amp;send_image=0&amp;cookie=1&amp;res=720x1280&amp;gt_ms=307&amp;): failed to open stream: HTTP request failed!  in piwik.php on line 128

Seeing this: [](http://stackoverflow.com/questions/697472/why-file-get-contents-returns-failed-to-open-stream-http-request-failed)

Is it possible that the "&amp;" in there are causing an issue, and they need to be removed, or something else needs to be encoded/decoded?

**Comment by mattab** [comment]
Are you using the latest version of the script? https://github.com/piwik/tracker-proxy/blob/master/piwik.php

**Comment by ytlevine** [comment]
Sorry, just seeing this - I had switched things around previously because of this: https://github.com/piwik/tracker-proxy/issues/6
Going to try the latest version of the script again.

**Comment by mattab** [comment]
@ytlevine let us know what you find

**Comment by ytlevine** [comment]
Still seeing a few of those errors, as well as these:

PHP Warning:  file_get_contents(): SSL: Handshake timed out in /home/stream/public_html/piwik.php on line 128
PHP Warning:  file_get_contents(): Failed to enable crypto in /home/stream/public_html/piwik.php on line 128

Any recommendations?

Thanks.

**Comment by ytlevine** [comment]
And not seeing that useCurl option in the version that you're referencing, looks like it was added here: https://github.com/braekling/WP-Piwik/commit/5673804d57e8c16c26a284be820e93239636b2f9#diff-0d764cbf675745f48b84472ba746a132
Going to try merging that in...

**Comment by ytlevine** [comment]
Switched over to the version you linked to for now, but I had issues previously with file_get_contents, we'll see what happens...

**Comment by ytlevine** [comment]
To follow up on this -
Still getting the errors, going to try @jsmad's code from here: https://github.com/piwik/tracker-proxy/issues/16#issuecomment-253337522

Wish it could officially be added in to the code...

**Comment by mattab** [comment]
See this PR: https://github.com/piwik/tracker-proxy/pull/3/files

we will merge it soon

**Comment by mattab** [comment]
Added support for CURL in: https://github.com/piwik/tracker-proxy/pull/21/files

if you manage to test the PR, feedback would be appreciated!
