### ISSUE TITLE
Piwik does not track custom vars if proxy script is used

### ISSUE THREAD

**Issue by braekling** [piwik/tracker-proxy#4]
While testing some refactored WP-Piwik functions on a local machine, I realized custom vars are not tracked if the proxy script is enabled.

My local tracking code looks like this:

```
var _paq = _paq || [];
_paq.push(['setCustomVariable',1, 'hello', 'world', 'page']);
_paq.push(['setCustomVariable',2, 'hello2', 'world2', 'page']);
_paq.push(['setCustomVariable',3, 'lorem', 'ipsum', 'page']);
_paq.push(['trackPageView']);
_paq.push(['enableLinkTracking']);
    (function() {
        var u="//192.168.33.10/wordpress/wp-content/plugins/wp-piwik/proxy/";
        _paq.push(['setTrackerUrl', u+'piwik.php']);
        _paq.push(['setSiteId', 1]);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.php';     
        s.parentNode.insertBefore(g,s);
    })();
```

If I don't use the proxy script (e.g., using js/index.php instead), the custom variables get tracked as expected.

Also see http://forum.piwik.org/read.php?2,103653

**Comment by diosmosis** [comment]
I cannot reproduce this problem, the code above results in successfully tracking the custom variables. Could you get the tracker URL used by the proxy in your test and post it w/ debug tracker output?

**Comment by braekling** [comment]
I'm not sure how to get the debug tracker output. Following the instructions, I added
```
[Tracker]
debug = 1
```
to my config.ini.php, but I can't see a difference in the response header.

Can you give me a hint how to get the debug output? Thank you!

**Comment by diosmosis** [comment]
That should actually do it. It should echo the output in the tracker request response. What do you see in the tracker output?

**Comment by braekling** [comment]
Ok, I created a new test environment (to make sure it was not a misconfiguration) and tried to collect everything I found ;-)

I'm using the latest Piwik (2.13.0), WP-Piwik in my second 1.0 beta release (0.10.0.1) containing the proxy script I pulled some days ago (extended by cURL support). 

This is my current tracking code:

```
  var _paq = _paq || [];
  _paq.push(['setCustomVariable',1, 'lorem', 'ipsum', 'page']);
_paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//192.168.33.10/wordpress/wp-content/plugins/wp-piwik/proxy/"
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.php'; s.parentNode.insertBefore(g,s);
  })();
```

This is the proxy script's header response does not contain any debug information.

```
Date	Sat, 02 May 2015 13:59:39 GMT
Content-Encoding	gzip
Last-Modified	Sat, 02 May 2015 13:59:40 GMT
Server	Apache/2.2.22 (Ubuntu)
X-Powered-By	PHP/5.3.10-1ubuntu3.18
Vary	Accept-Encoding
Content-Type	application/javascript; charset=UTF-8
Connection	Keep-Alive
Keep-Alive	timeout=5, max=91
Content-Length	15318
```

This is the proxy script's output is the full tracking client javascript code (I just post the first comment lines to avoid flooding this thread.).

```
/*!
 * Piwik - free/libre analytics platform
 *
 * JavaScript tracking client
 *
 * @link http://piwik.org
 * @source https://github.com/piwik/piwik/blob/master/js/piwik.js
 * @license http://piwik.org/free-software/bsd/ BSD-3 Clause (also in js/LICENSE.txt)
 * @license magnet:?xt=urn:btih:c80d50af7d3db9be66a4d0a86db0286e4fd33292&dn=bsd-3-clause.txt BSD-3-Clause
 */
if (typeof JSON2 !== "object") {
    JSON2 = window.JSON || {}
}(function() {
 ...
```

I checked the console, the headers and the script output itself, but it can't see any debug information. Well, I suppose I'm looking at the wrong place... I'm sorry :-(

**Comment by diosmosis** [comment]
Sorry for the late reply.

> This is the proxy script's header response does not contain any debug information.

The response header should not contain debug information. It's just an HTTP header.

> This is the proxy script's output is the full tracking client javascript code (I just post the first comment lines to avoid flooding this thread.).

This is the response if the request to the proxy script is not a tracking request, so I guess you sent a curl request to the proxy script w/ no query parameters?

To get debug tracking information, you can follow the following steps:

1. Enable debug logging for the tracker in Piwik (you already did this)
2. Get the tracking URL used by your JavaScript tracking code. (To do this, you can open a web page w/ the tracking code that triggers the bug for you in chrome w/ the inspector tools open. The network request should be captured and you can get the URL that way. You might also be able to see the debug response here, but I think chrome may not display it.)
3. invoke the tracker proxy script using the URL you found using `curl` or something like it. Please post the command you used w/ the output.

Also, if you are using a modified proxy script, please post it. Perhaps it will help.

**Comment by mattab** [comment]
Hi @braekling  

Do you still have this issue or was the problem solved?

**Comment by braekling** [comment]
@mattab Sorry for the delay. I will check again and tell you soon.

**Comment by mattab** [comment]
Hi @braekling  is this still an issue with 2.15.0?

**Comment by mattab** [comment]
I suppose it's not an issue anymore @braekling - if you have the issue please leave a comment or open a new issue, and we'll make sure to investigate :
