### ISSUE TITLE
Issue with file_get_contents and PHP 5.5

### ISSUE THREAD

**Issue by ytlevine** [piwik/tracker-proxy#6]
I recently upgraded my server to PHP 5.5, and since then (if I remember correctly), I've been seeing a lot of these errors in the error_log file (removed a bunch of info) - some with IPv4 addresses, some with IPv6:

PHP Warning:  file_get_contents(https://my/piwikurl.com/piwik.php?cip=x.x.x.x&amp;token_auth=auth&amp;action_name=action+name&amp;idsite=2&amp;rec=1&amp;r=033764&amp;h=11&amp;m=9&amp;s=22&amp;url=https%3A%2F%2Fmysite.com%2F&amp;_id=f18e523168d7055b&amp;_idts=1437481478&amp;_idvc=4&amp;_idn=0&amp;_refts=0&amp;_viewts=1437577763&amp;send_image=0&amp;pdf=1&amp;qt=0&amp;realp=0&amp;wma=0&amp;dir=0&amp;fla=1&amp;java=1&amp;gears=0&amp;ag=0&amp;cookie=1&amp;res=2000x1125&amp;gt_ms=445&amp;): failed to open stream: HTTP request failed!  in piwik.php on line 108

Is there any way to resolve this?
Would re-writing this to use curl instead of file_get_contents work more reliably?

Thanks!

**Comment by braekling** [comment]
Have a look at this pull: https://github.com/piwik/tracker-proxy/pull/3 Maybe this will work for you?

**Comment by ytlevine** [comment]
Didn't see that - I'll download the updated file and test with that, to see if that resolves the issue, and report back.
Thanks a lot!

**Comment by ytlevine** [comment]
So far seems OK, will keep an eye on it.
As a side point, I am using the WP-Piwik plugin, but couldn't get the proxy to work initially with the plugin, so I added the proxy tracking code manually.
I see that there were a bunch of fixes recently -  is this update included in that plugin? Or should I continue using it the way I have it set up, with the proxy tracking code added separately?
Thanks.

**Comment by ytlevine** [comment]
Got another error, still seems to at least partially be using file_get_contents...
Definitely getting less than before, and I don't think file_get_contents fails every time, but it still seems to be using that...

**Comment by braekling** [comment]
My changes will only use cURL if fopen is not available. To force the script to use cURL (or to prefer cURL at least), you have to invert the if-clause beginning in line 52. But I will think about a way to configure this in the file's header like everything else. 

And: Yes, this modified script is the one delivered with the WordPress plugin... It should work basically, but I'm currently testing because of an older issue I also posted here #4 .

**Comment by ytlevine** [comment]
Definitely seems to be working better for me with curl, so if there's a way to prioritize that, that would be best - thanks!
I can try rewriting that if, but I am not great with PHP, so if you have a chance to maybe make that available, that would be awesome...

Guess I'll continue using this for now - I also found that the script sometimes got blocked if it was named piwik.php, but when I renamed it pw.php, it seems to be fine, and I assume there's no easy way to do that with the plugin without it breaking on each update (tried emailing you about that as well)...

Thanks!

**Comment by ytlevine** [comment]
Still having the same issue.
How can I have the script use cURL by default?
Thanks a lot!

**Comment by braekling** [comment]
Look for...

```
function getContents($url, $options = false)
{
	if (ini_get('allow_url_fopen')) {
		$ctx = ($options?stream_context_create($options):NULL);
		return file_get_contents($url, 0, $ctx);
	} elseif (function_exists('curl_version'))
		return piwikFileGetContentsCurl($url, $options);
	else return 'Neither url_fopen nor cURL is available. Please enable at least one of them.';
}
```

Change to...

```
function getContents($url, $options = false)
{
	return piwikFileGetContentsCurl($url, $options);
}
```

That's it.

**Comment by ytlevine** [comment]
Thanks, will try that!

And any way to rename the script in the WordPress plugin to pw.php, or have a way to do that without breaking future updates?

**Comment by ytlevine** [comment]
And still getting an error:
PHP Warning:  curl_setopt(): You must pass either an object or an array with the CURLOPT_HTTPHEADER argument in pw.php on line 60

**Comment by braekling** [comment]
This should not affect the tracking. If you need to run your live system with enabled debugging, just comment line 60.

To use another file name, just create a symbolic link to the original proxy file. So your filename (= the link) persists if WP-Piwik is updated, but you also use the latest version (because it links to proxy/piwik.php): http://www.cyberciti.biz/faq/unix-creating-symbolic-link-ln-command/

**Comment by ytlevine** [comment]
Will try both, thanks a lot!

**Comment by ytlevine** [comment]
The link seemed to work - great idea, thanks!

And any plans of adding a config option to the proxy script, or at this point to the WP-Piwik plugin, to choose whether you want to use cURL or fopen? I'd switch to the plugin, just want to be able to control what it uses...

**Comment by braekling** [comment]
The plugin already allows to configure whether to use cURL or fopen, but this does not affect the proxy script, yet. I will consider this for the next release.

**Comment by mattab** [comment]
Added support for CURL in: https://github.com/piwik/tracker-proxy/pull/21/files

if you manage to test the PR, feedback would be appreciated!
