### ISSUE TITLE
If Piwik tracking server is down/unavailable, piwik.php should fail gracefuly, not 505

### ISSUE THREAD

**Issue by MagicFab** [piwik/tracker-proxy#8]
If the Piwik tracking server becomes unavailable, under normal implementation (using the standard .js tracker code), it's invoked and if it fails/is unavailable, there is no impact to the site / page being loaded. It will just not track stats anymore.

Using the tracker proxy, a 505 error is returned which in turn makes the site being tracked also return such error. 

The tracker-proxy code for this is ~line 78, this should fail gracefuly instead of making the main site being tracked completely unavailable.

**Comment by mattab** [comment]
Hi @MagicFab 

> Using the tracker proxy, a 505 error is returned which in turn makes the site being tracked also return such error. 

Do you have a screenshot or more information regarding the error triggered on the website?

**Comment by MagicFab** [comment]
No at the moment, this would require bringing down the content this was originally observed on. I started creating an environment to reproduce this but haven't finished yet.

**Comment by mattab** [comment]
re-opening, as we need to add automated tests to make sure we don't regress in the future

**Comment by MagicFab** [comment]
I've confirmed this fixes the issue as originally reported - thank you!

**Comment by mattab** [comment]
Good news @MagicFab 

re-opening, as we need to add automated tests to make sure we don't regress in the future
